/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Library : KettleUnitTest {
    val mockService = KettleMockService.forService<>()

    val service = MyService(mockService.getClient())


}
